name       : surfraw
version    : 2.3.0
release    : 2
source     :
    - https://github.com/JNRowe/surfraw/archive/surfraw-2.3.0.tar.gz : 66b2d5c89330f9e22e58440a1a8d86d0fda0d674c12be23df19e428d3eb9b766
license    : Public-Domain
component  : system.utils
summary    : Surfraw - Shell Users' Revolutionary Front Rage Against the Web
description: |
    Surfraw provides a fast unix command line interface to a variety of popular WWW search engines and other artifacts of power.
rundeps    :
    - links
setup      : |
    %reconfigure --with-graphical-browser=xdg-open \
        --with-text-browser=links
build      : |
    %make
install    : |
    %make_install
